version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: cilenco-radicale_server_1
      APP_PORT: 5232

  server:
    image: ghcr.io/kozea/radicale:3.8.1@sha256:54d9406cd30f9e206a9dd6d61dfac48da26b9afc37200e14f23beb8fafa7d11c
    volumes:
      - ${APP_DATA_DIR}/data/config:/etc/radicale
      - ${APP_DATA_DIR}/data/secrets:/etc/radicale/secrets
      - ${APP_DATA_DIR}/data/data:/var/lib/radicale
