#!/usr/bin/env bash
set -euo pipefail

echo "$LDAP_JWT_SECRET" > $DATA_DIR/secrets/ldap_secret

chown -R 1000:1000 "${UMBREL_DATA_DIR}/config"
chown -R 1000:1000 "${UMBREL_DATA_DIR}/secrets"
chown -R 1000:1000 "${UMBREL_DATA_DIR}/data"
