[auth]
type = ldap
ldap_uri = ldap://lldap:3890
ldap_base = dc=homelab,dc=com
ldap_reader_dn = uid=admin,ou=people,dc=homelab,dc=com
ldap_secret_file = /etc/radicale/secrets/ldap_secret
ldap_filter = (&(objectClass=person)(uid={0}))
lc_username = True
